spring:
  datasource:
    username: khahn
    url: jdbc:h2:mem:testdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: khahn
      password: skieth99
    realmImportFile: phoenix-realm.json
